# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  scheme = "Nextcloud"
  xcodeproj = "Nextcloud.xcodeproj"
  output_dir_path = "./build/sym"
  archive_path = "#{output_dir_path}/#{scheme}"

  desc "Build IPA for develop/feature/release (Alpha configuration, ad-hoc)"
  lane :build_alpha do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_API_KEY_ID"],
      issuer_id: ENV["APPSTORE_API_KEY_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_KEY_CONTENT"],
      duration: 1200, # optional (maximum 1200)
    )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.Widget",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.WidgetDashboardIntentHandler",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.Share",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.File-Provider-Extension",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.File-Provider-Extension-UI",
		  adhoc: true
	  )

    get_provisioning_profile(
		  api_key: api_key,
		  app_identifier: "com.viseven.ionos.easystorage.Notification-Service-Extension",
		  adhoc: true
	  )

    gym(
      scheme: scheme,
      configuration: "Alpha",
      output_directory: output_dir_path,
      derived_data_path: "./ipaDerivedData",
      output_name: scheme,
      archive_path: archive_path,
      export_method: "ad-hoc",
      silent: true,
      clean: true
    )
  end

  desc "Build IPA for beta (Beta configuration, ad-hoc)"
  lane :build_beta do
    gym(
      scheme: scheme,
      configuration: "Beta",
      output_directory: output_dir_path,
      derived_data_path: "./ipaDerivedData",
      output_name: scheme,
      archive_path: archive_path,
      export_method: "ad-hoc",
      silent: true,
      clean: true
    )
  end

  desc "Build .app for simulator (Alpha configuration). Prints only errors (requires xcbeautify: brew install xcbeautify)."
  lane :build_simulator do
    gym(
      scheme: scheme,
      configuration: "Alpha",
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator",
      derived_data_path: "./BuildForSimulator",
      silent: true,
      suppress_xcode_output: true,
      xcodebuild_formatter: "xcbeautify -qq"
    )
  end
end
